// frontend/admin-web/src/app/components/users/users.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { KeycloakAdminService, UserWithRoles, KeycloakRole } from '../../services/keycloak-admin.service';
import { KeycloakService } from '../../services/keycloak.service';

@Component({
  selector: 'app-users',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './template.html',
  styles: [`
    .users-page {
      padding: 32px 0;
    }

    .page-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 24px;
    }

    .page-header h1 {
      font-size: 24px;
      font-weight: 600;
      color: var(--gray-900);
      margin-bottom: 4px;
    }

    .page-header p {
      color: var(--gray-500);
    }

    .search-bar {
      display: flex;
      align-items: center;
      gap: 16px;
      margin-bottom: 24px;
    }

    .search-input-wrapper {
      flex: 1;
      max-width: 400px;
      position: relative;
    }

    .search-input-wrapper svg {
      position: absolute;
      left: 14px;
      top: 50%;
      transform: translateY(-50%);
      color: var(--gray-400);
    }

    .search-input-wrapper .form-control {
      padding-left: 44px;
    }

    .results-count {
      color: var(--gray-500);
      font-size: 14px;
    }

    .loading-state {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 60px;
      color: var(--gray-500);
    }

    .loading-state .spinner {
      margin-bottom: 16px;
    }

    .user-cell {
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .user-avatar {
      width: 40px;
      height: 40px;
      border-radius: 50%;
      background: linear-gradient(135deg, var(--primary-500), var(--primary-700));
      color: white;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 14px;
      font-weight: 600;
    }

    .user-info {
      display: flex;
      flex-direction: column;
    }

    .user-name {
      font-weight: 500;
      color: var(--gray-900);
    }

    .user-username {
      font-size: 12px;
      color: var(--gray-500);
    }

    .roles-cell {
      display: flex;
      flex-wrap: wrap;
      gap: 4px;
    }

    .role-badge {
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: 500;
      background: var(--primary-100);
      color: var(--primary-700);
    }

    .role-badge.admin {
      background: #f3e8ff;
      color: #9333ea;
    }

    .no-roles {
      color: var(--gray-400);
      font-size: 12px;
    }

    .action-buttons {
      display: flex;
      gap: 8px;
    }

    .action-buttons .btn {
      padding: 6px 8px;
    }

    .empty-state {
      text-align: center;
      padding: 40px;
      color: var(--gray-400);
    }

    .empty-state svg {
      margin-bottom: 12px;
    }

    /* Modal Styles */
    .modal-overlay {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(0, 0, 0, 0.5);
      display: flex;
      align-items: center;
      justify-content: center;
      z-index: 1000;
      padding: 20px;
    }

    .modal {
      background: white;
      border-radius: var(--radius-xl);
      width: 100%;
      max-width: 500px;
      max-height: 90vh;
      overflow-y: auto;
      animation: modalIn 0.2s ease;
    }

    .modal-sm {
      max-width: 400px;
    }

    @keyframes modalIn {
      from {
        opacity: 0;
        transform: scale(0.95);
      }
      to {
        opacity: 1;
        transform: scale(1);
      }
    }

    .modal-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 20px 24px;
      border-bottom: 1px solid var(--gray-200);
    }

    .modal-header h3 {
      font-size: 18px;
      font-weight: 600;
      color: var(--gray-900);
    }

    .modal-close {
      background: none;
      border: none;
      cursor: pointer;
      color: var(--gray-400);
      padding: 0;
    }

    .modal-close:hover {
      color: var(--gray-600);
    }

    .modal-body {
      padding: 24px;
    }

    .modal-footer {
      display: flex;
      justify-content: flex-end;
      gap: 12px;
      padding: 16px 24px;
      border-top: 1px solid var(--gray-200);
    }

    .form-row {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 16px;
    }

    .roles-select {
      display: flex;
      flex-wrap: wrap;
      gap: 12px;
    }

    .role-checkbox {
      display: flex;
      align-items: center;
      gap: 8px;
      cursor: pointer;
    }

    .role-checkbox input {
      width: 16px;
      height: 16px;
      cursor: pointer;
    }

    .role-label {
      font-size: 14px;
      color: var(--gray-700);
    }

    .checkbox-label {
      display: flex;
      align-items: center;
      gap: 8px;
      cursor: pointer;
      font-size: 14px;
      color: var(--gray-700);
    }

    .checkbox-label input {
      width: 16px;
      height: 16px;
    }

    .modal-info {
      font-size: 14px;
      color: var(--gray-600);
      margin-bottom: 20px;
    }

    .delete-warning {
      text-align: center;
      padding: 20px 0;
    }

    .delete-warning svg {
      color: var(--warning-500);
      margin-bottom: 16px;
    }

    .delete-warning p {
      color: var(--gray-700);
      margin-bottom: 4px;
    }

    .warning-text {
      font-size: 13px;
      color: var(--gray-500);
    }
  `]
})
export class UsersComponent implements OnInit {
  users: UserWithRoles[] = [];
  filteredUsers: UserWithRoles[] = [];
  availableRoles: KeycloakRole[] = [];
  searchQuery = '';
  isLoading = true;

  // Modal states
  showUserModal = false;
  showPasswordModal = false;
  showDeleteModal = false;
  isEditMode = false;
  isSaving = false;
  modalError = '';
  modalSuccess = '';

  // Form data
  selectedUser: UserWithRoles | null = null;
  formData = {
    username: '',
    email: '',
    firstName: '',
    lastName: '',
    password: '',
    roles: [] as string[],
    enabled: true,
    emailVerified: true,
  };
  newPassword = '';
  confirmPassword = '';
  temporaryPassword = false;

  constructor(
    private adminService: KeycloakAdminService,
    private keycloakService: KeycloakService
  ) {}

  async ngOnInit() {
    await this.loadUsers();
    await this.loadRoles();
  }

  async loadUsers() {
    this.isLoading = true;
    try {
      this.users = await this.adminService.getUsers();
      this.filteredUsers = this.users;
    } catch (error) {
      console.error('Failed to load users:', error);
    }
    this.isLoading = false;
  }

  async loadRoles() {
    try {
      this.availableRoles = await this.adminService.getRoles();
    } catch (error) {
      console.error('Failed to load roles:', error);
    }
  }

  onSearchChange(query: string) {
    const search = query.toLowerCase().trim();
    this.filteredUsers = this.users.filter(user => 
      user.username.toLowerCase().includes(search) ||
      user.email.toLowerCase().includes(search) ||
      (user.firstName && user.firstName.toLowerCase().includes(search)) ||
      (user.lastName && user.lastName.toLowerCase().includes(search))
    );
  }

  getInitials(firstName?: string, lastName?: string, username?: string): string {
    if (firstName && lastName) {
      return (firstName[0] + lastName[0]).toUpperCase();
    }
    if (firstName) return firstName[0].toUpperCase();
    if (username) return username.substring(0, 2).toUpperCase();
    return 'U';
  }

  formatDate(timestamp?: number): string {
    if (!timestamp) return 'N/A';
    return new Date(timestamp).toLocaleDateString();
  }

  // Modal operations
  openCreateModal() {
    this.isEditMode = false;
    this.selectedUser = null;
    this.formData = {
      username: '',
      email: '',
      firstName: '',
      lastName: '',
      password: '',
      roles: ['user'],
      enabled: true,
      emailVerified: true,
    };
    this.modalError = '';
    this.showUserModal = true;
  }

  openEditModal(user: UserWithRoles) {
    this.isEditMode = true;
    this.selectedUser = user;
    this.formData = {
      username: user.username,
      email: user.email,
      firstName: user.firstName || '',
      lastName: user.lastName || '',
      password: '',
      roles: [...user.roles],
      enabled: user.enabled,
      emailVerified: user.emailVerified || false,
    };
    this.modalError = '';
    this.showUserModal = true;
  }

  closeUserModal() {
    this.showUserModal = false;
    this.modalError = '';
  }

  toggleRole(roleName: string) {
    const index = this.formData.roles.indexOf(roleName);
    if (index === -1) {
      this.formData.roles.push(roleName);
    } else {
      this.formData.roles.splice(index, 1);
    }
  }

  async saveUser() {
    this.modalError = '';
    
    // Validation
    if (!this.formData.username || !this.formData.email) {
      this.modalError = 'Username and email are required';
      return;
    }
    
    if (!this.isEditMode && !this.formData.password) {
      this.modalError = 'Password is required';
      return;
    }

    this.isSaving = true;

    try {
      if (this.isEditMode && this.selectedUser) {
        // Update existing user
        await this.adminService.updateUser(this.selectedUser.id!, {
          firstName: this.formData.firstName,
          lastName: this.formData.lastName,
          email: this.formData.email,
          enabled: this.formData.enabled,
          emailVerified: this.formData.emailVerified,
        });

        // Update roles
        const currentRoles = this.selectedUser.roles;
        
        // Remove roles that are no longer selected
        for (const role of currentRoles) {
          if (!this.formData.roles.includes(role)) {
            await this.adminService.removeRole(this.selectedUser.id!, role);
          }
        }
        
        // Add new roles
        for (const role of this.formData.roles) {
          if (!currentRoles.includes(role)) {
            await this.adminService.assignRole(this.selectedUser.id!, role);
          }
        }
      } else {
        // Create new user
        await this.adminService.createUser({
          username: this.formData.username,
          email: this.formData.email,
          firstName: this.formData.firstName,
          lastName: this.formData.lastName,
          password: this.formData.password,
          enabled: this.formData.enabled,
          emailVerified: this.formData.emailVerified,
          roles: this.formData.roles,
        });
      }

      await this.loadUsers();
      this.closeUserModal();
    } catch (error: any) {
      this.modalError = error.message || 'Failed to save user';
    }

    this.isSaving = false;
  }

  // Password reset
  openPasswordModal(user: UserWithRoles) {
    this.selectedUser = user;
    this.newPassword = '';
    this.confirmPassword = '';
    this.temporaryPassword = false;
    this.modalError = '';
    this.modalSuccess = '';
    this.showPasswordModal = true;
  }

  closePasswordModal() {
    this.showPasswordModal = false;
    this.modalError = '';
    this.modalSuccess = '';
  }

  async resetPassword() {
    this.modalError = '';
    this.modalSuccess = '';

    if (!this.newPassword || !this.confirmPassword) {
      this.modalError = 'Please fill in all fields';
      return;
    }

    if (this.newPassword !== this.confirmPassword) {
      this.modalError = 'Passwords do not match';
      return;
    }

    if (this.newPassword.length < 8) {
      this.modalError = 'Password must be at least 8 characters';
      return;
    }

    this.isSaving = true;

    try {
      await this.adminService.resetUserPassword(this.selectedUser!.id!, this.newPassword, this.temporaryPassword);
      this.modalSuccess = 'Password reset successfully!';
      setTimeout(() => this.closePasswordModal(), 1500);
    } catch (error: any) {
      this.modalError = error.message || 'Failed to reset password';
    }

    this.isSaving = false;
  }

  // Delete user
  confirmDelete(user: UserWithRoles) {
    this.selectedUser = user;
    this.modalError = '';
    this.showDeleteModal = true;
  }

  closeDeleteModal() {
    this.showDeleteModal = false;
  }

  async deleteUser() {
    this.isSaving = true;

    try {
      await this.adminService.deleteUser(this.selectedUser!.id!);
      await this.loadUsers();
      this.closeDeleteModal();
    } catch (error: any) {
      this.modalError = error.message || 'Failed to delete user';
    }

    this.isSaving = false;
  }
}

// frontend/public-web/app/users/page.tsx
'use client';

import { useState, useEffect, useCallback } from 'react';
import { useAuth } from '@/lib/auth-context';
import { getUsers, createUser, updateUser, deleteUser, resetUserPassword, getRoles, assignRole, removeRole, UserWithRoles, KeycloakRole } from '@/lib/keycloak-admin';
import Navbar from '@/components/Navbar';
import { useRouter } from 'next/navigation';

export default function UsersPage() {
  const { isAuthenticated, isLoading: authLoading, hasRole } = useAuth();
  const router = useRouter();
  
  const [users, setUsers] = useState<UserWithRoles[]>([]);
  const [filteredUsers, setFilteredUsers] = useState<UserWithRoles[]>([]);
  const [roles, setRoles] = useState<KeycloakRole[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  
  // Modal states
  const [showUserModal, setShowUserModal] = useState(false);
  const [showPasswordModal, setShowPasswordModal] = useState(false);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [isEditMode, setIsEditMode] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [modalError, setModalError] = useState('');
  const [modalSuccess, setModalSuccess] = useState('');
  
  // Selected user for actions
  const [selectedUser, setSelectedUser] = useState<UserWithRoles | null>(null);
  
  // Form data
  const [formData, setFormData] = useState({
    username: '',
    email: '',
    firstName: '',
    lastName: '',
    password: '',
    roles: ['user'] as string[],
    enabled: true,
    emailVerified: true,
  });
  
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [temporaryPassword, setTemporaryPassword] = useState(false);

  // Check if user is admin
  useEffect(() => {
    if (!authLoading && (!isAuthenticated || !hasRole('admin'))) {
      router.push('/');
    }
  }, [authLoading, isAuthenticated, hasRole, router]);

  const loadUsers = useCallback(async () => {
    setIsLoading(true);
    try {
      const data = await getUsers();
      setUsers(data);
      setFilteredUsers(data);
    } catch (error) {
      console.error('Failed to load users:', error);
    }
    setIsLoading(false);
  }, []);

  const loadRoles = useCallback(async () => {
    try {
      const data = await getRoles();
      setRoles(data);
    } catch (error) {
      console.error('Failed to load roles:', error);
    }
  }, []);

  useEffect(() => {
    if (isAuthenticated && hasRole('admin')) {
      loadUsers();
      loadRoles();
    }
  }, [isAuthenticated, hasRole, loadUsers, loadRoles]);

  // Filter users
  useEffect(() => {
    const search = searchQuery.toLowerCase().trim();
    const filtered = users.filter(user => 
      user.username.toLowerCase().includes(search) ||
      user.email.toLowerCase().includes(search) ||
      (user.firstName && user.firstName.toLowerCase().includes(search)) ||
      (user.lastName && user.lastName.toLowerCase().includes(search))
    );
    setFilteredUsers(filtered);
  }, [searchQuery, users]);

  const getInitials = (firstName?: string, lastName?: string, username?: string) => {
    if (firstName && lastName) return (firstName[0] + lastName[0]).toUpperCase();
    if (firstName) return firstName[0].toUpperCase();
    if (username) return username.substring(0, 2).toUpperCase();
    return 'U';
  };

  const formatDate = (timestamp?: number) => {
    if (!timestamp) return 'N/A';
    return new Date(timestamp).toLocaleDateString();
  };

  // Modal handlers
  const openCreateModal = () => {
    setIsEditMode(false);
    setSelectedUser(null);
    setFormData({
      username: '',
      email: '',
      firstName: '',
      lastName: '',
      password: '',
      roles: ['user'],
      enabled: true,
      emailVerified: true,
    });
    setModalError('');
    setShowUserModal(true);
  };

  const openEditModal = (user: UserWithRoles) => {
    setIsEditMode(true);
    setSelectedUser(user);
    setFormData({
      username: user.username,
      email: user.email,
      firstName: user.firstName || '',
      lastName: user.lastName || '',
      password: '',
      roles: [...user.roles],
      enabled: user.enabled,
      emailVerified: user.emailVerified || false,
    });
    setModalError('');
    setShowUserModal(true);
  };

  const closeUserModal = () => {
    setShowUserModal(false);
    setModalError('');
  };

  const toggleRole = (roleName: string) => {
    setFormData(prev => ({
      ...prev,
      roles: prev.roles.includes(roleName)
        ? prev.roles.filter(r => r !== roleName)
        : [...prev.roles, roleName]
    }));
  };

  const saveUser = async () => {
    setModalError('');
    
    if (!formData.username || !formData.email) {
      setModalError('Username and email are required');
      return;
    }
    
    if (!isEditMode && !formData.password) {
      setModalError('Password is required');
      return;
    }

    setIsSaving(true);

    try {
      if (isEditMode && selectedUser) {
        await updateUser(selectedUser.id!, {
          firstName: formData.firstName,
          lastName: formData.lastName,
          email: formData.email,
          enabled: formData.enabled,
          emailVerified: formData.emailVerified,
        });

        const currentRoles = selectedUser.roles;
        
        for (const role of currentRoles) {
          if (!formData.roles.includes(role)) {
            await removeRole(selectedUser.id!, role);
          }
        }
        
        for (const role of formData.roles) {
          if (!currentRoles.includes(role)) {
            await assignRole(selectedUser.id!, role);
          }
        }
      } else {
        await createUser({
          username: formData.username,
          email: formData.email,
          firstName: formData.firstName,
          lastName: formData.lastName,
          password: formData.password,
          enabled: formData.enabled,
          emailVerified: formData.emailVerified,
          roles: formData.roles,
        });
      }

      await loadUsers();
      closeUserModal();
    } catch (error: any) {
      setModalError(error.message || 'Failed to save user');
    }

    setIsSaving(false);
  };

  // Password reset
  const openPasswordModal = (user: UserWithRoles) => {
    setSelectedUser(user);
    setNewPassword('');
    setConfirmPassword('');
    setTemporaryPassword(false);
    setModalError('');
    setModalSuccess('');
    setShowPasswordModal(true);
  };

  const closePasswordModal = () => {
    setShowPasswordModal(false);
    setModalError('');
    setModalSuccess('');
  };

  const handleResetPassword = async () => {
    setModalError('');
    setModalSuccess('');

    if (!newPassword || !confirmPassword) {
      setModalError('Please fill in all fields');
      return;
    }

    if (newPassword !== confirmPassword) {
      setModalError('Passwords do not match');
      return;
    }

    if (newPassword.length < 8) {
      setModalError('Password must be at least 8 characters');
      return;
    }

    setIsSaving(true);

    try {
      await resetUserPassword(selectedUser!.id!, newPassword, temporaryPassword);
      setModalSuccess('Password reset successfully!');
      setTimeout(() => closePasswordModal(), 1500);
    } catch (error: any) {
      setModalError(error.message || 'Failed to reset password');
    }

    setIsSaving(false);
  };

  // Delete user
  const openDeleteModal = (user: UserWithRoles) => {
    setSelectedUser(user);
    setModalError('');
    setShowDeleteModal(true);
  };

  const closeDeleteModal = () => {
    setShowDeleteModal(false);
  };

  const handleDeleteUser = async () => {
    setIsSaving(true);

    try {
      await deleteUser(selectedUser!.id!);
      await loadUsers();
      closeDeleteModal();
    } catch (error: any) {
      setModalError(error.message || 'Failed to delete user');
    }

    setIsSaving(false);
  };

  if (authLoading || !isAuthenticated || !hasRole('admin')) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Navbar />
        <div className="flex items-center justify-center h-[calc(100vh-64px)]">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />
      
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex justify-between items-start mb-6">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">User Management</h1>
            <p className="text-gray-500 mt-1">Manage users and their roles in Keycloak</p>
          </div>
          <button
            onClick={openCreateModal}
            className="inline-flex items-center gap-2 px-4 py-2 bg-primary-600 text-white rounded-lg font-medium hover:bg-primary-700 transition-colors"
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="12" y1="5" x2="12" y2="19"/>
              <line x1="5" y1="12" x2="19" y2="12"/>
            </svg>
            Add User
          </button>
        </div>

        {/* Search */}
        <div className="flex items-center gap-4 mb-6">
          <div className="relative flex-1 max-w-md">
            <svg className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="11" cy="11" r="8"/>
              <line x1="21" y1="21" x2="16.65" y2="16.65"/>
            </svg>
            <input
              type="text"
              placeholder="Search users..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
            />
          </div>
          <span className="text-gray-500 text-sm">{filteredUsers.length} users found</span>
        </div>

        {/* Loading */}
        {isLoading && (
          <div className="flex flex-col items-center justify-center py-12">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
            <p className="text-gray-500 mt-4">Loading users...</p>
          </div>
        )}

        {/* Users Table */}
        {!isLoading && (
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50 border-b border-gray-200">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">User</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Roles</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Created</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {filteredUsers.map((user) => (
                    <tr key={user.id} className="hover:bg-gray-50">
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary-500 to-primary-700 text-white flex items-center justify-center text-sm font-medium">
                            {getInitials(user.firstName, user.lastName, user.username)}
                          </div>
                          <div>
                            <div className="font-medium text-gray-900">{user.firstName} {user.lastName}</div>
                            <div className="text-sm text-gray-500">@{user.username}</div>
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-gray-700">{user.email}</td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="flex gap-1">
                          {user.roles.map(role => (
                            <span
                              key={role}
                              className={`px-2 py-0.5 rounded text-xs font-medium ${
                                role === 'admin' ? 'bg-purple-100 text-purple-700' : 'bg-blue-100 text-blue-700'
                              }`}
                            >
                              {role}
                            </span>
                          ))}
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className={`px-2 py-1 rounded text-xs font-medium ${
                          user.enabled ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
                        }`}>
                          {user.enabled ? 'Active' : 'Disabled'}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-gray-500">{formatDate(user.createdTimestamp)}</td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="flex gap-2">
                          <button
                            onClick={() => openEditModal(user)}
                            className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded"
                            title="Edit"
                          >
                            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/>
                              <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>
                            </svg>
                          </button>
                          <button
                            onClick={() => openPasswordModal(user)}
                            className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded"
                            title="Reset Password"
                          >
                            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <rect x="3" y="11" width="18" height="11" rx="2" ry="2"/>
                              <path d="M7 11V7a5 5 0 0 1 10 0v4"/>
                            </svg>
                          </button>
                          <button
                            onClick={() => openDeleteModal(user)}
                            className="p-2 text-red-500 hover:text-red-700 hover:bg-red-50 rounded"
                            title="Delete"
                          >
                            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                              <polyline points="3 6 5 6 21 6"/>
                              <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>
                            </svg>
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                  {filteredUsers.length === 0 && (
                    <tr>
                      <td colSpan={6} className="px-6 py-12 text-center text-gray-500">
                        No users found
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </main>

      {/* Create/Edit User Modal */}
      {showUserModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={closeUserModal}>
          <div className="bg-white rounded-xl w-full max-w-lg max-h-[90vh] overflow-y-auto" onClick={e => e.stopPropagation()}>
            <div className="flex justify-between items-center p-6 border-b border-gray-200">
              <h3 className="text-lg font-semibold text-gray-900">{isEditMode ? 'Edit User' : 'Create New User'}</h3>
              <button onClick={closeUserModal} className="text-gray-400 hover:text-gray-600">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                </svg>
              </button>
            </div>
            
            <div className="p-6 space-y-4">
              {modalError && <div className="bg-red-50 text-red-700 p-3 rounded-lg text-sm">{modalError}</div>}
              
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">First Name</label>
                  <input
                    type="text"
                    value={formData.firstName}
                    onChange={e => setFormData({ ...formData, firstName: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Last Name</label>
                  <input
                    type="text"
                    value={formData.lastName}
                    onChange={e => setFormData({ ...formData, lastName: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Username *</label>
                <input
                  type="text"
                  value={formData.username}
                  onChange={e => setFormData({ ...formData, username: e.target.value })}
                  disabled={isEditMode}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent disabled:bg-gray-50"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Email *</label>
                <input
                  type="email"
                  value={formData.email}
                  onChange={e => setFormData({ ...formData, email: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                />
              </div>

              {!isEditMode && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Password *</label>
                  <input
                    type="password"
                    value={formData.password}
                    onChange={e => setFormData({ ...formData, password: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  />
                </div>
              )}

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Roles</label>
                <div className="flex flex-wrap gap-3">
                  {roles.map(role => (
                    <label key={role.id} className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={formData.roles.includes(role.name)}
                        onChange={() => toggleRole(role.name)}
                        className="w-4 h-4"
                      />
                      <span className="text-sm text-gray-700">{role.name}</span>
                    </label>
                  ))}
                </div>
              </div>

              <div className="flex gap-6">
                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={formData.enabled}
                    onChange={e => setFormData({ ...formData, enabled: e.target.checked })}
                    className="w-4 h-4"
                  />
                  <span className="text-sm text-gray-700">Enabled</span>
                </label>
                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={formData.emailVerified}
                    onChange={e => setFormData({ ...formData, emailVerified: e.target.checked })}
                    className="w-4 h-4"
                  />
                  <span className="text-sm text-gray-700">Email Verified</span>
                </label>
              </div>
            </div>

            <div className="flex justify-end gap-3 p-6 border-t border-gray-200">
              <button onClick={closeUserModal} className="px-4 py-2 text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200">
                Cancel
              </button>
              <button
                onClick={saveUser}
                disabled={isSaving}
                className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 disabled:opacity-50"
              >
                {isSaving ? 'Saving...' : (isEditMode ? 'Update User' : 'Create User')}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Password Reset Modal */}
      {showPasswordModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={closePasswordModal}>
          <div className="bg-white rounded-xl w-full max-w-md" onClick={e => e.stopPropagation()}>
            <div className="flex justify-between items-center p-6 border-b border-gray-200">
              <h3 className="text-lg font-semibold text-gray-900">Reset Password</h3>
              <button onClick={closePasswordModal} className="text-gray-400 hover:text-gray-600">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                </svg>
              </button>
            </div>
            
            <div className="p-6 space-y-4">
              <p className="text-gray-600">Reset password for <strong>{selectedUser?.username}</strong></p>
              
              {modalError && <div className="bg-red-50 text-red-700 p-3 rounded-lg text-sm">{modalError}</div>}
              {modalSuccess && <div className="bg-green-50 text-green-700 p-3 rounded-lg text-sm">{modalSuccess}</div>}
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">New Password</label>
                <input
                  type="password"
                  value={newPassword}
                  onChange={e => setNewPassword(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Confirm Password</label>
                <input
                  type="password"
                  value={confirmPassword}
                  onChange={e => setConfirmPassword(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                />
              </div>

              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={temporaryPassword}
                  onChange={e => setTemporaryPassword(e.target.checked)}
                  className="w-4 h-4"
                />
                <span className="text-sm text-gray-700">Temporary password (user must change on next login)</span>
              </label>
            </div>

            <div className="flex justify-end gap-3 p-6 border-t border-gray-200">
              <button onClick={closePasswordModal} className="px-4 py-2 text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200">
                Cancel
              </button>
              <button
                onClick={handleResetPassword}
                disabled={isSaving}
                className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 disabled:opacity-50"
              >
                {isSaving ? 'Resetting...' : 'Reset Password'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {showDeleteModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={closeDeleteModal}>
          <div className="bg-white rounded-xl w-full max-w-sm" onClick={e => e.stopPropagation()}>
            <div className="flex justify-between items-center p-6 border-b border-gray-200">
              <h3 className="text-lg font-semibold text-gray-900">Delete User</h3>
              <button onClick={closeDeleteModal} className="text-gray-400 hover:text-gray-600">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                </svg>
              </button>
            </div>
            
            <div className="p-6 text-center">
              <div className="w-12 h-12 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-red-600">
                  <circle cx="12" cy="12" r="10"/>
                  <line x1="12" y1="8" x2="12" y2="12"/>
                  <line x1="12" y1="16" x2="12.01" y2="16"/>
                </svg>
              </div>
              <p className="text-gray-700 mb-2">
                Are you sure you want to delete <strong>{selectedUser?.username}</strong>?
              </p>
              <p className="text-sm text-gray-500">This action cannot be undone.</p>
            </div>

            <div className="flex justify-end gap-3 p-6 border-t border-gray-200">
              <button onClick={closeDeleteModal} className="px-4 py-2 text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200">
                Cancel
              </button>
              <button
                onClick={handleDeleteUser}
                disabled={isSaving}
                className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 disabled:opacity-50"
              >
                {isSaving ? 'Deleting...' : 'Delete User'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
