// frontend/admin-web/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, ActivatedRoute, RouterLink } from '@angular/router';
import { KeycloakService } from '../../services/keycloak.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './template.html',
  styles: [`
    .login-page {
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      background: var(--gray-50);
    }

    .login-container {
      display: flex;
      width: 100%;
      max-width: 1000px;
      min-height: 600px;
      background: white;
      border-radius: var(--radius-xl);
      box-shadow: var(--shadow-lg);
      overflow: hidden;
      margin: 20px;
    }

    .login-branding {
      flex: 1;
      background: linear-gradient(135deg, var(--primary-600), var(--primary-800));
      padding: 60px;
      display: flex;
      align-items: center;
      color: white;
    }

    .branding-content h1 {
      font-size: 36px;
      font-weight: 700;
      margin-bottom: 16px;
    }

    .branding-content p {
      font-size: 16px;
      opacity: 0.9;
      line-height: 1.6;
      margin-bottom: 40px;
    }

    .features-list {
      display: flex;
      flex-direction: column;
      gap: 20px;
    }

    .feature-item {
      display: flex;
      align-items: center;
      gap: 16px;
      font-size: 15px;
    }

    .feature-item svg {
      opacity: 0.8;
    }

    .login-form-container {
      flex: 1;
      padding: 60px;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .login-form {
      width: 100%;
      max-width: 360px;
    }

    .form-header {
      text-align: center;
      margin-bottom: 32px;
    }

    .form-header h2 {
      font-size: 24px;
      font-weight: 600;
      color: var(--gray-900);
      margin-bottom: 8px;
    }

    .form-header p {
      color: var(--gray-500);
      font-size: 14px;
    }

    .input-icon-wrapper {
      position: relative;
      display: flex;
      align-items: center;
    }

    .input-icon-wrapper svg {
      position: absolute;
      left: 14px;
      color: var(--gray-400);
    }

    .input-icon-wrapper .form-control {
      padding-left: 44px;
      padding-right: 44px;
    }

    .password-toggle {
      position: absolute;
      right: 14px;
      background: none;
      border: none;
      cursor: pointer;
      color: var(--gray-400);
      padding: 0;
      display: flex;
    }

    .password-toggle:hover {
      color: var(--gray-600);
    }

    .btn-block {
      width: 100%;
    }

    .loading-content {
      display: flex;
      align-items: center;
      gap: 8px;
    }

    .spinner-sm {
      width: 18px;
      height: 18px;
      animation: spin 0.8s linear infinite;
    }

    .form-footer {
      text-align: center;
      margin-top: 24px;
      font-size: 14px;
      color: var(--gray-500);
    }

    .form-footer a {
      color: var(--primary-600);
      text-decoration: none;
      font-weight: 500;
    }

    .form-footer a:hover {
      text-decoration: underline;
    }

    .test-credentials {
      margin-top: 32px;
      border: 1px solid var(--gray-200);
      border-radius: var(--radius-lg);
      overflow: hidden;
    }

    .credentials-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 12px 16px;
      background: var(--gray-50);
      cursor: pointer;
      font-size: 13px;
      font-weight: 500;
      color: var(--gray-600);
    }

    .credentials-header svg {
      transition: transform 0.2s;
    }

    .credentials-header svg.rotated {
      transform: rotate(180deg);
    }

    .credentials-content {
      padding: 12px;
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .credential-btn {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 10px 12px;
      background: var(--gray-50);
      border: 1px solid var(--gray-200);
      border-radius: var(--radius-md);
      cursor: pointer;
      font-size: 13px;
      color: var(--gray-700);
      transition: all 0.2s;
    }

    .credential-btn:hover {
      background: var(--gray-100);
      border-color: var(--gray-300);
    }

    .role-badge {
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: 600;
      text-transform: uppercase;
    }

    .role-badge.user {
      background: var(--primary-100);
      color: var(--primary-700);
    }

    .role-badge.admin {
      background: #f3e8ff;
      color: #9333ea;
    }

    @media (max-width: 768px) {
      .login-container {
        flex-direction: column;
      }
      .login-branding {
        padding: 40px;
      }
      .login-form-container {
        padding: 40px;
      }
      .branding-content h1 {
        font-size: 28px;
      }
    }
  `]
})
export class LoginComponent implements OnInit {
  email = '';
  password = '';
  error = '';
  isLoading = false;
  showPassword = false;
  showCredentials = false;
  returnUrl = '/dashboard';

  constructor(
    private keycloakService: KeycloakService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit() {
    this.returnUrl = this.route.snapshot.queryParams['returnUrl'] || '/dashboard';
  }

  onSubmit() {
    if (!this.email || !this.password) {
      this.error = 'Please fill in all fields';
      return;
    }

    this.error = '';
    this.isLoading = true;

    this.keycloakService.login(this.email, this.password).subscribe({
      next: () => {
        this.router.navigate([this.returnUrl]);
      },
      error: (err) => {
        this.isLoading = false;
        if (err.error?.error_description) {
          this.error = err.error.error_description;
        } else if (err.error?.message) {
          this.error = err.error.message;
        } else {
          this.error = 'Invalid email or password. Please try again.';
        }
      }
    });
  }

  fillTestUser() {
    this.email = 'user@example.com';
    this.password = 'Password123!';
  }

  fillTestAdmin() {
    this.email = 'admin@example.com';
    this.password = 'Admin123!';
  }
}

// frontend/public-web/app/login/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/lib/auth-context';
import { config } from '@/lib/config';

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [showCredentials, setShowCredentials] = useState(false);
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  
  const { login, isAuthenticated, isLoading: authLoading } = useAuth();
  const router = useRouter();
  const searchParams = useSearchParams();
  const returnUrl = searchParams.get('returnUrl') || '/dashboard';

  useEffect(() => {
    if (!authLoading && isAuthenticated) {
      router.push(returnUrl);
    }
  }, [authLoading, isAuthenticated, router, returnUrl]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      await login(email, password);
      router.push(returnUrl);
    } catch (err: any) {
      setError(err.message || 'Invalid email or password. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const fillTestUser = () => {
    setEmail(config.testCredentials.user.email);
    setPassword(config.testCredentials.user.password);
  };

  const fillTestAdmin = () => {
    setEmail(config.testCredentials.admin.email);
    setPassword(config.testCredentials.admin.password);
  };

  if (authLoading || isAuthenticated) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4">
      <div className="w-full max-w-5xl flex bg-white rounded-2xl shadow-xl overflow-hidden">
        {/* Left Side - Branding */}
        <div className="hidden lg:flex lg:flex-1 bg-gradient-to-br from-primary-600 to-primary-800 p-12 text-white">
          <div className="max-w-md">
            <h1 className="text-4xl font-bold mb-4">Welcome Back</h1>
            <p className="text-primary-100 text-lg mb-8">
              Sign in to access the Microservices Platform and manage your applications.
            </p>
            
            <div className="space-y-4">
              {[
                { icon: '🔐', text: 'Secure Authentication' },
                { icon: '👥', text: 'User Management' },
                { icon: '📊', text: 'Real-time Analytics' },
              ].map((item, i) => (
                <div key={i} className="flex items-center gap-3">
                  <span className="text-2xl">{item.icon}</span>
                  <span className="text-primary-100">{item.text}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right Side - Login Form */}
        <div className="flex-1 p-8 lg:p-12">
          <div className="max-w-sm mx-auto">
            <div className="text-center mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-2">Sign In</h2>
              <p className="text-gray-500">Enter your credentials to continue</p>
            </div>

            {error && (
              <div className="bg-red-50 text-red-700 p-4 rounded-lg mb-6 text-sm flex items-start gap-3">
                <svg className="w-5 h-5 mt-0.5 flex-shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <circle cx="12" cy="12" r="10"/>
                  <line x1="15" y1="9" x2="9" y2="15"/>
                  <line x1="9" y1="9" x2="15" y2="15"/>
                </svg>
                {error}
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-5">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Email Address
                </label>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="Enter your email"
                  required
                  disabled={isLoading}
                  className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition-all disabled:bg-gray-50"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Password
                </label>
                <div className="relative">
                  <input
                    type={showPassword ? 'text' : 'password'}
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="Enter your password"
                    required
                    disabled={isLoading}
                    className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition-all disabled:bg-gray-50 pr-12"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                  >
                    {showPassword ? (
                      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94"/>
                        <line x1="1" y1="1" x2="23" y2="23"/>
                      </svg>
                    ) : (
                      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>
                        <circle cx="12" cy="12" r="3"/>
                      </svg>
                    )}
                  </button>
                </div>
              </div>

              <button
                type="submit"
                disabled={isLoading || !email || !password}
                className="w-full py-3 bg-primary-600 text-white rounded-lg font-medium hover:bg-primary-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {isLoading ? (
                  <>
                    <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none"/>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
                    </svg>
                    Signing in...
                  </>
                ) : (
                  'Sign In'
                )}
              </button>
            </form>

            <div className="mt-6 text-center text-sm text-gray-500">
              Don't have an account?{' '}
              <Link href="/register" className="text-primary-600 font-medium hover:underline">
                Create one
              </Link>
            </div>

            {/* Test Credentials */}
            <div className="mt-8 border border-gray-200 rounded-lg overflow-hidden">
              <button
                type="button"
                onClick={() => setShowCredentials(!showCredentials)}
                className="w-full px-4 py-3 bg-gray-50 text-left flex items-center justify-between text-sm font-medium text-gray-600 hover:bg-gray-100"
              >
                Test Credentials
                <svg className={`w-4 h-4 transition-transform ${showCredentials ? 'rotate-180' : ''}`} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M6 9l6 6 6-6"/>
                </svg>
              </button>
              {showCredentials && (
                <div className="p-4 space-y-2">
                  <button
                    type="button"
                    onClick={fillTestUser}
                    className="w-full flex items-center gap-3 px-3 py-2 bg-gray-50 rounded-lg text-sm hover:bg-gray-100 text-left"
                  >
                    <span className="px-2 py-0.5 bg-blue-100 text-blue-700 rounded text-xs font-medium">User</span>
                    user@example.com
                  </button>
                  <button
                    type="button"
                    onClick={fillTestAdmin}
                    className="w-full flex items-center gap-3 px-3 py-2 bg-gray-50 rounded-lg text-sm hover:bg-gray-100 text-left"
                  >
                    <span className="px-2 py-0.5 bg-purple-100 text-purple-700 rounded text-xs font-medium">Admin</span>
                    admin@example.com
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
