// frontend/public-web/app/profile/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/lib/auth-context';
import { getUserDisplayName, getToken } from '@/lib/keycloak';
import { updateUser, changeOwnPassword } from '@/lib/keycloak-admin';
import Navbar from '@/components/Navbar';

export default function ProfilePage() {
  const { user, isAuthenticated, isLoading, logout, refreshSession } = useAuth();
  const router = useRouter();
  const [tokenPreview, setTokenPreview] = useState('');
  
  // Modal states
  const [showEditModal, setShowEditModal] = useState(false);
  const [showPasswordModal, setShowPasswordModal] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [modalError, setModalError] = useState('');
  const [modalSuccess, setModalSuccess] = useState('');
  
  // Edit form
  const [editForm, setEditForm] = useState({
    firstName: '',
    lastName: '',
    email: '',
  });
  
  // Password form
  const [passwordForm, setPasswordForm] = useState({
    currentPassword: '',
    newPassword: '',
    confirmPassword: '',
  });

  useEffect(() => {
    if (!isLoading && !isAuthenticated) {
      router.push('/login?returnUrl=/profile');
    }
    
    const token = getToken();
    if (token) {
      setTokenPreview(token.substring(0, 80) + '...');
    }
  }, [isLoading, isAuthenticated, router]);

  const getUserInitials = () => {
    const name = getUserDisplayName(user);
    const parts = name.split(' ');
    if (parts.length >= 2) return (parts[0][0] + parts[1][0]).toUpperCase();
    return name.substring(0, 2).toUpperCase();
  };

  const getUserRoles = () => {
    return user?.realm_access?.roles?.filter(r => !r.startsWith('default-')) || [];
  };

  // Edit Profile
  const openEditProfile = () => {
    setEditForm({
      firstName: user?.given_name || '',
      lastName: user?.family_name || '',
      email: user?.email || '',
    });
    setModalError('');
    setModalSuccess('');
    setShowEditModal(true);
  };

  const closeEditModal = () => {
    setShowEditModal(false);
    setModalError('');
    setModalSuccess('');
  };

  const saveProfile = async () => {
    setModalError('');
    setIsSaving(true);

    try {
      const userId = user?.sub;
      if (!userId) throw new Error('User ID not found');

      await updateUser(userId, {
        firstName: editForm.firstName,
        lastName: editForm.lastName,
      });

      // Refresh user info
      await refreshSession();
      setModalSuccess('Profile updated successfully!');
      setTimeout(() => closeEditModal(), 1500);
    } catch (error: any) {
      setModalError(error.message || 'Failed to update profile');
    }

    setIsSaving(false);
  };

  // Change Password
  const openChangePassword = () => {
    setPasswordForm({
      currentPassword: '',
      newPassword: '',
      confirmPassword: '',
    });
    setModalError('');
    setModalSuccess('');
    setShowPasswordModal(true);
  };

  const closePasswordModal = () => {
    setShowPasswordModal(false);
    setModalError('');
    setModalSuccess('');
  };

  const getPasswordStrength = () => {
    let strength = 0;
    if (passwordForm.newPassword.length >= 8) strength += 25;
    if (/[a-z]/.test(passwordForm.newPassword)) strength += 25;
    if (/[A-Z]/.test(passwordForm.newPassword)) strength += 25;
    if (/[0-9]/.test(passwordForm.newPassword)) strength += 25;
    return strength;
  };

  const getStrengthClass = () => {
    const strength = getPasswordStrength();
    if (strength <= 25) return 'bg-red-500';
    if (strength <= 75) return 'bg-yellow-500';
    return 'bg-green-500';
  };

  const getStrengthText = () => {
    const strength = getPasswordStrength();
    if (strength <= 25) return 'Weak';
    if (strength <= 75) return 'Medium';
    return 'Strong';
  };

  const handleChangePassword = async () => {
    setModalError('');

    if (!passwordForm.currentPassword || !passwordForm.newPassword || !passwordForm.confirmPassword) {
      setModalError('Please fill in all fields');
      return;
    }

    if (passwordForm.newPassword !== passwordForm.confirmPassword) {
      setModalError('New passwords do not match');
      return;
    }

    if (passwordForm.newPassword.length < 8) {
      setModalError('Password must be at least 8 characters');
      return;
    }

    setIsSaving(true);

    try {
      const token = getToken();
      if (!token) throw new Error('No authentication token');

      await changeOwnPassword(token, passwordForm);
      setModalSuccess('Password changed successfully!');
      setTimeout(() => closePasswordModal(), 1500);
    } catch (error: any) {
      setModalError(error.message || 'Failed to change password');
    }

    setIsSaving(false);
  };

  const handleLogout = async () => {
    await logout();
    router.push('/');
  };

  const handleRefresh = async () => {
    await refreshSession();
    const token = getToken();
    if (token) {
      setTokenPreview(token.substring(0, 80) + '...');
    }
  };

  if (isLoading || !isAuthenticated) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Navbar />
        <div className="flex items-center justify-center h-[calc(100vh-64px)]">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />
      
      <main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-gray-900">Profile Settings</h1>
          <p className="text-gray-500 mt-1">Manage your account settings and preferences</p>
        </div>

        <div className="grid lg:grid-cols-3 gap-6">
          {/* Profile Info Card */}
          <div className="lg:col-span-2 bg-white rounded-xl shadow-sm border border-gray-200">
            <div className="p-6 border-b border-gray-100 flex justify-between items-center">
              <h2 className="text-lg font-semibold text-gray-900">Profile Information</h2>
              <button
                onClick={openEditProfile}
                className="inline-flex items-center gap-2 px-3 py-1.5 text-sm bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200"
              >
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/>
                  <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>
                </svg>
                Edit Profile
              </button>
            </div>
            
            <div className="p-6">
              <div className="flex items-center gap-6 pb-6 border-b border-gray-100">
                <div className="w-20 h-20 rounded-full bg-gradient-to-br from-blue-500 to-blue-700 text-white flex items-center justify-center text-2xl font-semibold">
                  {getUserInitials()}
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-gray-900">{getUserDisplayName(user)}</h3>
                  <p className="text-gray-500">{user?.email}</p>
                  <div className="flex gap-2 mt-2">
                    {getUserRoles().map(role => (
                      <span
                        key={role}
                        className={`px-3 py-1 rounded-full text-xs font-medium ${
                          role === 'admin' ? 'bg-purple-100 text-purple-700' : 'bg-blue-100 text-blue-700'
                        }`}
                      >
                        {role}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              <div className="mt-6 space-y-4">
                <div className="flex justify-between py-3 border-b border-gray-100">
                  <span className="text-gray-500">User ID</span>
                  <span className="font-mono text-sm text-gray-700">{user?.sub}</span>
                </div>
                <div className="flex justify-between py-3 border-b border-gray-100">
                  <span className="text-gray-500">Username</span>
                  <span className="text-gray-700">{user?.preferred_username}</span>
                </div>
                <div className="flex justify-between py-3 border-b border-gray-100">
                  <span className="text-gray-500">Email</span>
                  <span className="text-gray-700">{user?.email}</span>
                </div>
                <div className="flex justify-between py-3 border-b border-gray-100">
                  <span className="text-gray-500">Email Verified</span>
                  <span className={user?.email_verified ? 'text-green-600' : 'text-yellow-600'}>
                    {user?.email_verified ? '✓ Verified' : 'Pending'}
                  </span>
                </div>
                <div className="flex justify-between py-3 border-b border-gray-100">
                  <span className="text-gray-500">First Name</span>
                  <span className="text-gray-700">{user?.given_name || '-'}</span>
                </div>
                <div className="flex justify-between py-3">
                  <span className="text-gray-500">Last Name</span>
                  <span className="text-gray-700">{user?.family_name || '-'}</span>
                </div>
              </div>
            </div>
          </div>

          {/* Actions Card */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200">
            <div className="p-6 border-b border-gray-100">
              <h2 className="text-lg font-semibold text-gray-900">Account Actions</h2>
            </div>
            
            <div className="p-4 space-y-2">
              <button
                onClick={openChangePassword}
                className="w-full flex items-center gap-3 p-4 rounded-lg hover:bg-gray-50 transition-colors text-left"
              >
                <div className="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center">
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-gray-600">
                    <rect x="3" y="11" width="18" height="11" rx="2" ry="2"/>
                    <path d="M7 11V7a5 5 0 0 1 10 0v4"/>
                  </svg>
                </div>
                <div className="flex-1">
                  <p className="font-medium text-gray-900">Change Password</p>
                  <p className="text-sm text-gray-500">Update your account password</p>
                </div>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-gray-400">
                  <path d="M9 18l6-6-6-6"/>
                </svg>
              </button>

              <button
                onClick={handleRefresh}
                className="w-full flex items-center gap-3 p-4 rounded-lg hover:bg-gray-50 transition-colors text-left"
              >
                <div className="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center">
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-gray-600">
                    <polyline points="23 4 23 10 17 10"/>
                    <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/>
                  </svg>
                </div>
                <div className="flex-1">
                  <p className="font-medium text-gray-900">Refresh Session</p>
                  <p className="text-sm text-gray-500">Renew your access token</p>
                </div>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-gray-400">
                  <path d="M9 18l6-6-6-6"/>
                </svg>
              </button>

              <button
                onClick={handleLogout}
                className="w-full flex items-center gap-3 p-4 rounded-lg hover:bg-red-50 transition-colors text-left"
              >
                <div className="w-10 h-10 bg-red-100 rounded-lg flex items-center justify-center">
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-red-600">
                    <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/>
                    <polyline points="16 17 21 12 16 7"/>
                    <line x1="21" y1="12" x2="9" y2="12"/>
                  </svg>
                </div>
                <div className="flex-1">
                  <p className="font-medium text-red-600">Sign Out</p>
                  <p className="text-sm text-red-400">Sign out of your account</p>
                </div>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-red-400">
                  <path d="M9 18l6-6-6-6"/>
                </svg>
              </button>
            </div>
          </div>

          {/* Token Info */}
          <div className="lg:col-span-3 bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-2">Access Token</h2>
            <p className="text-sm text-gray-500 mb-4">
              Your JWT token is used for API authentication with your microservices.
            </p>
            <div className="bg-gray-900 rounded-lg p-4 overflow-x-auto">
              <code className="text-green-400 text-xs break-all">
                {tokenPreview || 'No token available'}
              </code>
            </div>
          </div>
        </div>
      </main>

      {/* Edit Profile Modal */}
      {showEditModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={closeEditModal}>
          <div className="bg-white rounded-xl w-full max-w-md" onClick={e => e.stopPropagation()}>
            <div className="flex justify-between items-center p-6 border-b border-gray-200">
              <h3 className="text-lg font-semibold text-gray-900">Edit Profile</h3>
              <button onClick={closeEditModal} className="text-gray-400 hover:text-gray-600">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                </svg>
              </button>
            </div>
            
            <div className="p-6 space-y-4">
              {modalError && <div className="bg-red-50 text-red-700 p-3 rounded-lg text-sm">{modalError}</div>}
              {modalSuccess && <div className="bg-green-50 text-green-700 p-3 rounded-lg text-sm">{modalSuccess}</div>}
              
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">First Name</label>
                  <input
                    type="text"
                    value={editForm.firstName}
                    onChange={e => setEditForm({ ...editForm, firstName: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Last Name</label>
                  <input
                    type="text"
                    value={editForm.lastName}
                    onChange={e => setEditForm({ ...editForm, lastName: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
                <input
                  type="email"
                  value={editForm.email}
                  disabled
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-50 text-gray-500"
                />
                <p className="text-xs text-gray-500 mt-1">Email cannot be changed</p>
              </div>
            </div>

            <div className="flex justify-end gap-3 p-6 border-t border-gray-200">
              <button onClick={closeEditModal} className="px-4 py-2 text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200">
                Cancel
              </button>
              <button
                onClick={saveProfile}
                disabled={isSaving}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50"
              >
                {isSaving ? 'Saving...' : 'Save Changes'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Change Password Modal */}
      {showPasswordModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={closePasswordModal}>
          <div className="bg-white rounded-xl w-full max-w-md" onClick={e => e.stopPropagation()}>
            <div className="flex justify-between items-center p-6 border-b border-gray-200">
              <h3 className="text-lg font-semibold text-gray-900">Change Password</h3>
              <button onClick={closePasswordModal} className="text-gray-400 hover:text-gray-600">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                </svg>
              </button>
            </div>
            
            <div className="p-6 space-y-4">
              {modalError && <div className="bg-red-50 text-red-700 p-3 rounded-lg text-sm">{modalError}</div>}
              {modalSuccess && <div className="bg-green-50 text-green-700 p-3 rounded-lg text-sm">{modalSuccess}</div>}
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Current Password</label>
                <input
                  type="password"
                  value={passwordForm.currentPassword}
                  onChange={e => setPasswordForm({ ...passwordForm, currentPassword: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">New Password</label>
                <input
                  type="password"
                  value={passwordForm.newPassword}
                  onChange={e => setPasswordForm({ ...passwordForm, newPassword: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
                {passwordForm.newPassword && (
                  <div className="mt-2 flex items-center gap-2">
                    <div className="flex-1 h-1 bg-gray-200 rounded-full overflow-hidden">
                      <div
                        className={`h-full transition-all ${getStrengthClass()}`}
                        style={{ width: `${getPasswordStrength()}%` }}
                      ></div>
                    </div>
                    <span className="text-xs text-gray-500">{getStrengthText()}</span>
                  </div>
                )}
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Confirm New Password</label>
                <input
                  type="password"
                  value={passwordForm.confirmPassword}
                  onChange={e => setPasswordForm({ ...passwordForm, confirmPassword: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                />
                {passwordForm.confirmPassword && passwordForm.newPassword !== passwordForm.confirmPassword && (
                  <p className="text-red-500 text-xs mt-1">Passwords do not match</p>
                )}
              </div>

              <div className="bg-gray-50 p-3 rounded-lg">
                <p className="text-xs font-medium text-gray-700 mb-2">Password requirements:</p>
                <ul className="text-xs text-gray-500 space-y-1">
                  <li className={passwordForm.newPassword.length >= 8 ? 'text-green-600' : ''}>
                    {passwordForm.newPassword.length >= 8 ? '✓' : '○'} At least 8 characters
                  </li>
                  <li className={/[a-z]/.test(passwordForm.newPassword) ? 'text-green-600' : ''}>
                    {/[a-z]/.test(passwordForm.newPassword) ? '✓' : '○'} One lowercase letter
                  </li>
                  <li className={/[A-Z]/.test(passwordForm.newPassword) ? 'text-green-600' : ''}>
                    {/[A-Z]/.test(passwordForm.newPassword) ? '✓' : '○'} One uppercase letter
                  </li>
                  <li className={/[0-9]/.test(passwordForm.newPassword) ? 'text-green-600' : ''}>
                    {/[0-9]/.test(passwordForm.newPassword) ? '✓' : '○'} One number
                  </li>
                </ul>
              </div>
            </div>

            <div className="flex justify-end gap-3 p-6 border-t border-gray-200">
              <button onClick={closePasswordModal} className="px-4 py-2 text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200">
                Cancel
              </button>
              <button
                onClick={handleChangePassword}
                disabled={isSaving}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50"
              >
                {isSaving ? 'Changing...' : 'Change Password'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// frontend/admin-web/src/app/components/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { KeycloakService, UserInfo } from '../../services/keycloak.service';
import { KeycloakAdminService } from '../../services/keycloak-admin.service';

// Helper function to get token (will be added)
declare function getToken(): string | null;

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './template.html',
  styles: [`
    .profile-page {
      padding: 32px 0;
    }

    .page-header {
      margin-bottom: 24px;
    }

    .page-header h1 {
      font-size: 24px;
      font-weight: 600;
      color: var(--gray-900);
      margin-bottom: 4px;
    }

    .page-header p {
      color: var(--gray-500);
    }

    .profile-grid {
      display: grid;
      grid-template-columns: 2fr 1fr;
      gap: 24px;
    }

    .profile-info-card {
      grid-column: span 2;
    }

    .profile-avatar-section {
      display: flex;
      align-items: center;
      gap: 24px;
      padding-bottom: 24px;
      margin-bottom: 24px;
      border-bottom: 1px solid var(--gray-200);
    }

    .avatar-large {
      width: 80px;
      height: 80px;
      border-radius: 50%;
      background: linear-gradient(135deg, var(--primary-500), var(--primary-700));
      color: white;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 28px;
      font-weight: 600;
    }

    .avatar-info h4 {
      font-size: 20px;
      font-weight: 600;
      color: var(--gray-900);
      margin-bottom: 4px;
    }

    .avatar-info p {
      color: var(--gray-500);
      margin-bottom: 8px;
    }

    .user-roles {
      display: flex;
      gap: 8px;
    }

    .role-badge {
      padding: 4px 10px;
      border-radius: 9999px;
      font-size: 12px;
      font-weight: 500;
      background: var(--primary-100);
      color: var(--primary-700);
    }

    .role-badge.admin {
      background: #f3e8ff;
      color: #9333ea;
    }

    .info-list {
      display: flex;
      flex-direction: column;
    }

    .info-item {
      display: flex;
      justify-content: space-between;
      padding: 12px 0;
      border-bottom: 1px solid var(--gray-100);
    }

    .info-label {
      color: var(--gray-500);
      font-size: 14px;
    }

    .info-value {
      color: var(--gray-900);
      font-weight: 500;
      font-size: 14px;
    }

    .info-value.code {
      font-family: monospace;
      font-size: 12px;
    }

    .info-value.verified {
      color: var(--success-600);
    }

    .info-value.not-verified {
      color: var(--warning-600);
    }

    .action-list {
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .action-item {
      display: flex;
      align-items: center;
      gap: 12px;
      width: 100%;
      padding: 16px;
      background: var(--gray-50);
      border: 1px solid var(--gray-200);
      border-radius: var(--radius-lg);
      cursor: pointer;
      text-align: left;
      transition: all 0.2s;
    }

    .action-item:hover {
      background: var(--gray-100);
      border-color: var(--gray-300);
    }

    .action-item.danger {
      color: var(--error-600);
    }

    .action-item.danger:hover {
      background: #fef2f2;
      border-color: #fecaca;
    }

    .action-icon {
      width: 40px;
      height: 40px;
      border-radius: var(--radius-md);
      background: white;
      display: flex;
      align-items: center;
      justify-content: center;
      border: 1px solid var(--gray-200);
    }

    .action-content {
      flex: 1;
    }

    .action-title {
      display: block;
      font-weight: 500;
      color: var(--gray-900);
      font-size: 14px;
    }

    .action-desc {
      font-size: 12px;
      color: var(--gray-500);
    }

    .chevron {
      color: var(--gray-400);
    }

    .session-card {
      grid-column: span 2;
    }

    .token-display {
      background: var(--gray-900);
      padding: 16px;
      border-radius: var(--radius-md);
      overflow-x: auto;
    }

    .token-display code {
      color: #22c55e;
      font-size: 12px;
      white-space: nowrap;
    }

    .session-note {
      margin-top: 12px;
      font-size: 12px;
      color: var(--gray-500);
    }

    /* Modal Styles */
    .modal-overlay {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(0, 0, 0, 0.5);
      display: flex;
      align-items: center;
      justify-content: center;
      z-index: 1000;
      padding: 20px;
    }

    .modal {
      background: white;
      border-radius: var(--radius-xl);
      width: 100%;
      max-width: 480px;
      max-height: 90vh;
      overflow-y: auto;
      animation: modalIn 0.2s ease;
    }

    @keyframes modalIn {
      from { opacity: 0; transform: scale(0.95); }
      to { opacity: 1; transform: scale(1); }
    }

    .modal-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 20px 24px;
      border-bottom: 1px solid var(--gray-200);
    }

    .modal-header h3 {
      font-size: 18px;
      font-weight: 600;
      color: var(--gray-900);
    }

    .modal-close {
      background: none;
      border: none;
      cursor: pointer;
      color: var(--gray-400);
      padding: 0;
    }

    .modal-body {
      padding: 24px;
    }

    .modal-footer {
      display: flex;
      justify-content: flex-end;
      gap: 12px;
      padding: 16px 24px;
      border-top: 1px solid var(--gray-200);
    }

    .form-row {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 16px;
    }

    .form-hint {
      font-size: 12px;
      color: var(--gray-500);
      margin-top: 4px;
    }

    .form-error {
      color: var(--error-500);
      font-size: 12px;
      margin-top: 4px;
    }

    .password-strength {
      margin-top: 8px;
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .strength-bar {
      flex: 1;
      height: 4px;
      background: var(--gray-200);
      border-radius: 2px;
      overflow: hidden;
    }

    .strength-fill {
      height: 100%;
      transition: width 0.3s, background 0.3s;
    }

    .strength-fill.weak { background: var(--error-500); }
    .strength-fill.medium { background: var(--warning-500); }
    .strength-fill.strong { background: var(--success-500); }

    .strength-text {
      font-size: 12px;
      color: var(--gray-500);
      min-width: 50px;
    }

    .password-requirements {
      background: var(--gray-50);
      padding: 12px 16px;
      border-radius: var(--radius-md);
      margin-top: 16px;
    }

    .requirements-title {
      font-size: 12px;
      font-weight: 500;
      color: var(--gray-700);
      margin-bottom: 8px;
    }

    .password-requirements ul {
      list-style: none;
      padding: 0;
      margin: 0;
    }

    .password-requirements li {
      font-size: 12px;
      color: var(--gray-500);
      padding: 2px 0;
      padding-left: 20px;
      position: relative;
    }

    .password-requirements li::before {
      content: '○';
      position: absolute;
      left: 0;
    }

    .password-requirements li.met {
      color: var(--success-600);
    }

    .password-requirements li.met::before {
      content: '●';
    }

    @media (max-width: 768px) {
      .profile-grid {
        grid-template-columns: 1fr;
      }
      .session-card, .profile-info-card {
        grid-column: span 1;
      }
      .profile-avatar-section {
        flex-direction: column;
        text-align: center;
      }
    }
  `]
})
export class ProfileComponent implements OnInit {
  userInfo: UserInfo | null = null;
  tokenPreview = '';

  // Modal states
  showEditModal = false;
  showPasswordModal = false;
  isSaving = false;
  modalError = '';
  modalSuccess = '';

  // Edit form
  editForm = {
    firstName: '',
    lastName: '',
    email: '',
  };

  // Password form
  passwordForm = {
    currentPassword: '',
    newPassword: '',
    confirmPassword: '',
  };

  constructor(
    private keycloakService: KeycloakService,
    private adminService: KeycloakAdminService,
    private router: Router
  ) {}

  async ngOnInit() {
    this.userInfo = await this.keycloakService.loadUserInfo();
    const token = this.keycloakService.getToken();
    if (token) {
      this.tokenPreview = token.substring(0, 80) + '...';
    }
  }

  getUserInitials(): string {
    const name = this.userInfo?.name || this.userInfo?.preferred_username || 'U';
    const parts = name.split(' ');
    if (parts.length >= 2) {
      return (parts[0][0] + parts[1][0]).toUpperCase();
    }
    return name.substring(0, 2).toUpperCase();
  }

  getUserRoles(): string[] {
    return this.userInfo?.realm_access?.roles?.filter(r => !r.startsWith('default-')) || [];
  }

  // Edit Profile
  openEditProfile() {
    this.editForm = {
      firstName: this.userInfo?.given_name || '',
      lastName: this.userInfo?.family_name || '',
      email: this.userInfo?.email || '',
    };
    this.modalError = '';
    this.modalSuccess = '';
    this.showEditModal = true;
  }

  closeEditModal() {
    this.showEditModal = false;
    this.modalError = '';
    this.modalSuccess = '';
  }

  async saveProfile() {
    this.modalError = '';
    this.isSaving = true;

    try {
      const token = this.keycloakService.getToken();
      if (!token) {
        throw new Error('No authentication token');
      }

      // Get user ID from userInfo
      const userId = this.userInfo?.sub;
      if (!userId) {
        throw new Error('User ID not found');
      }

      // Update user profile via admin API
      await this.adminService.updateUser(userId, {
        firstName: this.editForm.firstName,
        lastName: this.editForm.lastName,
      });

      // Reload user info
      this.userInfo = await this.keycloakService.loadUserInfo();
      this.modalSuccess = 'Profile updated successfully!';
      setTimeout(() => this.closeEditModal(), 1500);
    } catch (error: any) {
      this.modalError = error.message || 'Failed to update profile';
    }

    this.isSaving = false;
  }

  // Change Password
  openChangePassword() {
    this.passwordForm = {
      currentPassword: '',
      newPassword: '',
      confirmPassword: '',
    };
    this.modalError = '';
    this.modalSuccess = '';
    this.showPasswordModal = true;
  }

  closePasswordModal() {
    this.showPasswordModal = false;
    this.modalError = '';
    this.modalSuccess = '';
  }

  get hasLowercase(): boolean {
    return /[a-z]/.test(this.passwordForm.newPassword);
  }

  get hasUppercase(): boolean {
    return /[A-Z]/.test(this.passwordForm.newPassword);
  }

  get hasNumber(): boolean {
    return /[0-9]/.test(this.passwordForm.newPassword);
  }

  get passwordStrength(): number {
    let strength = 0;
    if (this.passwordForm.newPassword.length >= 8) strength += 25;
    if (/[a-z]/.test(this.passwordForm.newPassword)) strength += 25;
    if (/[A-Z]/.test(this.passwordForm.newPassword)) strength += 25;
    if (/[0-9]/.test(this.passwordForm.newPassword)) strength += 25;
    return strength;
  }

  get strengthClass(): string {
    if (this.passwordStrength <= 25) return 'weak';
    if (this.passwordStrength <= 75) return 'medium';
    return 'strong';
  }

  get strengthText(): string {
    if (this.passwordStrength <= 25) return 'Weak';
    if (this.passwordStrength <= 75) return 'Medium';
    return 'Strong';
  }

  async changePassword() {
    this.modalError = '';

    if (!this.passwordForm.currentPassword || !this.passwordForm.newPassword || !this.passwordForm.confirmPassword) {
      this.modalError = 'Please fill in all fields';
      return;
    }

    if (this.passwordForm.newPassword !== this.passwordForm.confirmPassword) {
      this.modalError = 'New passwords do not match';
      return;
    }

    if (this.passwordForm.newPassword.length < 8) {
      this.modalError = 'Password must be at least 8 characters';
      return;
    }

    this.isSaving = true;

    try {
      const token = this.keycloakService.getToken();
      if (!token) {
        throw new Error('No authentication token');
      }

      await this.adminService.changeOwnPassword(token, {
        currentPassword: this.passwordForm.currentPassword,
        newPassword: this.passwordForm.newPassword,
        confirmPassword: this.passwordForm.confirmPassword,
      });

      this.modalSuccess = 'Password changed successfully!';
      setTimeout(() => this.closePasswordModal(), 1500);
    } catch (error: any) {
      this.modalError = error.message || 'Failed to change password';
    }

    this.isSaving = false;
  }

  // Session management
  async refreshSession() {
    await this.keycloakService.refreshToken().toPromise();
    const token = this.keycloakService.getToken();
    if (token) {
      this.tokenPreview = token.substring(0, 80) + '...';
    }
  }

  logout() {
    this.keycloakService.logout().subscribe(() => {
      this.router.navigate(['/']);
    });
  }
}
